# Generated by Django 4.2 on 2023-04-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Critical', 'Critical'), ('<Medium', 'Medium'), ('Low', 'Low'), ('Best Rffort', 'Best effort')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Ready to go', 'Ready to go'), ('In progress', 'In progress'), ('Completed', 'Completed'), ('stuck', 'Stuck')], max_length=100, null=True),
        ),
    ]
