# Generated by Django 4.2 on 2023-04-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Critical', 'Critical'), ('Medium', 'Medium'), ('Low', 'Low'), ('Best Effort', 'Best effort')], max_length=100, null=True),
        ),
    ]
